### PR TITLE
Add support to SSH Config and sudo mode

### PR DESCRIPTION
**Pull request by michelcaradec**
Hello Michael,

First of all, I would like to thank you for pushing online this very nice tool.  
I like its simplicity, and immediately found a daily usage in it.

I quickly realized I was missing few features (mostly related to my own development environment):

- Ability to connect using an **SSH Config** entry (in such case, no password is required when a private key is used).
- If the user used to SSH connect is not member of the group `docker`, but is a `sudoers`, then running the Docker command prefixed with **sudo** is required.

I added support to both features, which involved a bit of refactoring.

I allowed myself to increase the version number (but it is in a separate commit, so it can be easily reversed).

I hope the coding style used matches your own standards.

Best regards.

Michel

### CODE REVIEW

**Comment by michelcaradec** [comment]
I realize I only increased the version number in the `__init__.py` file, but I forgot to do so in the file `pyproject.toml`.

**Comment by mikeckennedy** [comment]
Hi @michelcaradec Thank you. Quick glance this looks great. Let me dig into it a bit when I'm at my desk and I'll get it merged.

**Comment by mikeckennedy** [comment]
This looks good, thank you @michelcaradec. I'd like to update the --ssh-config help message. How does this look?

```python
help='Pass this flag to treat the host as a ssh config entry (e.g. {username}@{host})'
```

**Comment by michelcaradec** [comment]
> This looks good, thank you @michelcaradec. I'd like to update the --ssh-config help message. How does this look?
> 
> ```python
> help='Pass this flag to treat the host as a ssh config entry (e.g. {username}@{host})'
> ```

Oh yes, this is much better than my original explanation, which was more like a docstring thing. :-)

Thank you.

**Pull request merged**
